Repository BendroCorp/bendrocorp-api, pull requests merged in 2020-11, with the labels that each got.

#360 Fixed error message
  app/controllers/pages_controller.rb
Labels: hacktoberfest-accepted

#359 Fixed welcome message
  app/controllers/pages_controller.rb
Labels: hacktoberfest-accepted

#363 Initial move of the legacy/main API to Kubernetes
  .github/workflows/ruby-master.yml
  .github/workflows/ruby-pr.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/controllers/reports_controller.rb
  k8/bendro_api_v1_api_deployment.yml
  k8/bendro_api_v1_service.yml
Labels: enhancement

#365 Deployment fix
  k8/bendro_api_v1_api_deployment.yml
Labels: enhancement

#366 Fix for #364
  app/controllers/reports_controller.rb
Labels: bug

#367 Allow field descriptor classes sorting by date
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/field_descriptor_class.rb
  db/migrate/20200119232655_create_field_descriptor_classes.rb
  db/schema.rb
  deploy.sh
Labels: db changes completed, db changes required, enabler, enhancement

#368 Enabled other services
  .github/workflows/ruby-master.yml
  k8/bendro_api_v1_rpush_deployment.yml
  k8/bendro_api_v1_sidekiq_deployment.yml
Labels: enhancement

#369 Added imagemagick to dockerfile
  Dockerfile
Labels: bug

#370 Fixes
  .github/workflows/ruby-master.yml
  app/controllers/users_controller.rb
  k8/bendro_api_v1_api_deployment.yml
Labels: bug

#371 Fixed more archived report issues
  app/controllers/reports_controller.rb
Labels: bug

#372 Added refresh_token to refresh fetch
  app/controllers/sessions_controller.rb
Labels: enhancement

#373 Fixes for token endpoint
  app/controllers/sessions_controller.rb
Labels: bug
